# Generated by Django 4.1.3 on 2022-11-17 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('particular', models.TextField(max_length=500)),
                ('ledger_folio', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('entry_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 13, 39, 35, 300568), null=True)),
                ('update_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 13, 39, 35, 300568), null=True)),
            ],
            options={
                'db_table': 'ims_items',
            },
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='first_name',
            new_name='fist_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mini.category'),
        ),
    ]
