# Generated by Django 4.1.3 on 2022-11-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0003_alter_item_entry_date_alter_item_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
