# Generated by Django 4.1.3 on 2022-11-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0004_rename_fist_name_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
